apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.0.1
          env:
            - name: CLUSTER_NAME
              value: $CLUSTER_NAME
            - name: SERVER_BASEPATH
              value: $SERVER_BASEPATH
            - name: SERVER_NAME
              value: $SERVER_NAME
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 5601
              name: http
