apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  labels:
    component: kibana
spec:
  type: ClusterIP
  selector:
    component: kibana
  ports:
  - name: http
    port: $SERVICE_PORT
    targetPort: 5601
